<main class="admin-page">
    <h2>Gestionnaire d'événement</h2>
    <div class="container-fluid">

        <div class="card">
            <div class="card-header bg-dark text-light">Modifier l'événement</div>
            <div class="card-body">

                <form method="POST" action="./admin-event-editor">
                    <div class="form-group">
                        <label for="titleEvent">Titre de la session</label>
                        <input type="text" class="form-control" id="titleEvent" name="titleEvent" placeholder="ex: Loup Garou" value="<?= htmlspecialchars($event['title']) ?>">
                    </div>
                    <div class="form-group">
                        <label for="eventDifficulty">Difficulté</label>
                        <input class="form-control" id="eventDifficulty" name="eventDifficulty" placeholder="Facile" value="<?= htmlspecialchars($event['difficulty']) ?>">
                    </div>
                    <div class="form-group">
                        <label for="eventLevel">Niveau Recommandé</label>
                        <input type="number" class="form-control" id="eventLevel" name="eventLevel" placeholder="1" min="1" max="20" value="<?= htmlspecialchars($event['level']) ?>">
                    </div>
                    <div class="form-group">
                        <label for="eventDate">Date de l'événement</label>
                        <input type="date" class="form-control" id="eventDate" name="eventDate" value="<?= $event['day'] ?>">
                    </div>
                    <div class="form-group">
                        <label for="eventStart">Heure de début</label>
                        <input type="time" class="form-control" id="eventStart" name="eventStart" value="<?= $event['startHour'] ?>">
                    </div>
                    <div class="form-group">
                        <label for="eventEnd">Heure de fin</label>
                        <input type="time" class="form-control" id="eventEnd" name="eventEnd" value="<?= $event['endHour'] ?>">
                    </div>


                    <button type="submit" class="btn btn-primary">Modifier</button>
                </form>

            </div><!-- end of card body -->
        </div><!-- end of card container -->

    </div><!-- end of main container -->
</main>