<main>
    <section class="home">
        <h2>Bienvenue dans l'antre du kraken</h2>
        <img src="./Views/img/ogre.jpg" alt="ogre sur un jeu de plateau">
        <img src="./Views/img/red_dice.jpg" alt="dés rouges">
        <img src="./Views/img/dragon.jpg" alt="dragon sur un jeu de plateau">
        <p>
            Kraken Play est un site entièrement consacré à l'univers du célèbre jeu de rôles "Donjons & Dragons". Vous pourrez y retrouver une boutique pour acheter des dés polyédriques de toutes sortes de couleur.
        </p>
        <p>
            Vous ne trouvez pas la couleur qui vous plait ? Allez sur notre atelier de personnalisation de dé et confectionnez votre dé personnalisé !
        </p>
        <a href="./custom" class="button">Atelier personnalisation</a>
    </section>
</main>