<main>

    <?php if (isset($errors)) : ?>
        <article class="form-error">
            <h2>Erreur</h2>
            <p>Veuillez vérifier le(s) champ(s) suivant(s): </p>
            <ul>
                <?php foreach ($errors as $error) : ?>
                    <li><?= $error ?></li>
                <?php endforeach; ?>
            </ul>
        </article>
    <?php endif; ?>

    <form id="register" method="POST" action="./register">
        <fieldset>
            <legend>Informations</legend>

            <label for="first-name">Prénom</label>
            <input type="text" name="firstname" id="first-name" placeholder="Prénom">

            <label for="last-name">Nom</label>
            <input type="text" name="lastname" id="last-name" placeholder="Nom">

            <label for="date">Date de Naissance</label>
            <select id="date" name="day">
                <?php for ($i = 1; $i <= 31; $i++) : ?>
                    <option value="<?= $i ?>"><?= $i ?></option>
                <?php endfor; ?>
            </select>

            <select name="month">
                <option value="1">Janvier</option>
                <option value="2">Février</option>
                <option value="3">Mars</option>
                <option value="4">Avril</option>
                <option value="5">Mai</option>
                <option value="6">Juin</option>
                <option value="7">Juillet</option>
                <option value="8">Août</option>
                <option value="9">Septembre</option>
                <option value="10">Octobre</option>
                <option value="11">Novembre</option>
                <option value="12">Décembre</option>
            </select>

            <select name="year">
                <?php for ($i = date('Y'); $i >= 1920; $i--) : ?>
                    <option value="<?= $i ?>"><?= $i ?></option>
                <?php endfor; ?>
            </select>

            <label for="address">Adresse</label>
            <input type="text" name="address" id="address" placeholder="Adresse">

            <label for="post-code">Code Postal</label>
            <input type="text" name="postcode" id="post-code" placeholder="Code Postal">

            <label for="city">Ville</label>
            <input type="text" name="city" id="city" placeholder="Ville">

            <label for="country">Pays</label>
            <input type="text" name="country" id="country" placeholder="Pays">
        </fieldset>

        <fieldset>
            <legend>Identifiants de connexion</legend>

            <label for="email">Adresse e-mail</label>
            <input type="email" name="email" id="email" placeholder="e-mail@dnd.com">

            <label for="password">Mot de passe</label>
            <input type="password" name="password" id="password" placeholder="au moins 8 caractères">
        </fieldset>

        <button type="submit" id="register-button">S'inscrire</button>
        <button type="reset">Remettre à zéro</button>
    </form>

    <p>Déjà inscrit ? Connectez-vous <a href="./login">ici</a>.</p>
    <script src="./Views/js/register.js"></script>
</main>